name: Repo Build To Amplify
on: 
  push:
    branches:
    - main
  workflow_dispatch:
  
env:
  FILE_NAME: ${{ github.event.repository.name }}-build.zip
  APP_ID: ${{ vars.APP_ID }}
  
jobs:
  Build:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
    - run: mkdir artifact
    - run: cd dist; zip -r ../artifact/$FILE_NAME ./*; cd ..;
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: artifact/
        retention-days: 1
    - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - run: unzip awscliv2.zip
    - run: sudo ./aws/install --update
    - run: aws --version
    - run: aws configure set aws_access_key_id ${{ secrets.AWS_KEY_ID }} --profile ${{ vars.PROFILE }}
    - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile ${{ vars.PROFILE }}
    - run: aws configure set region ${{ vars.REGION }} --profile ${{ vars.PROFILE }}
    - run: aws s3api put-object --bucket ${{ vars.AWS_BUCKET }} --key $FILE_NAME --body ./artifact/$FILE_NAME --profile ${{ vars.PROFILE }}
    - run: aws amplify start-deployment --app-id $APP_ID --branch-name manual --source-url s3://${{ vars.AWS_BUCKET}}/$FILE_NAME
      
