on: 
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  setup_environment:
    name: Setup Node.js environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile
    - run: vite build
    - run: ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.head_ref }}.${{ github.sha }}
        path: /dist/
  
