on: 
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  setup_environment:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-build
        path: dist/
  
